name: bmdt
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - bleach=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.25
  - jsonschema=4.23.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - openssl=3.0.15
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=24.2
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - readline=8.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.2
      - alabaster==0.7.16
      - anyascii==0.3.2
      - asgiref==3.8.1
      - astroid==3.3.5
      - autoflake==2.0.1
      - babel==2.16.0
      - beautifulsoup4==4.12.2
      - biomart==0.9.2
      - biopython==1.81
      - black==23.1.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colour==0.1.5
      - contourpy==1.3.1
      - coverage==7.2.1
      - cycler==0.12.1
      - dash==2.9.2
      - dash-bio==1.0.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - distlib==0.3.9
      - django==4.1.7
      - docutils==0.20.1
      - et-xmlfile==2.0.0
      - fastobo==0.12.3
      - filelock==3.16.1
      - flask==2.2.5
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - geoparse==2.0.4
      - gseapy==1.0.5
      - identify==2.6.2
      - idna==3.10
      - igraph==0.10.4
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - isort==5.12.0
      - itsdangerous==2.2.0
      - joblib==1.2.0
      - jsonschema-specifications==2024.10.1
      - kaleido==0.2.1
      - kiwisolver==1.4.7
      - lark==1.2.2
      - llvmlite==0.40.1
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nodeenv==1.9.1
      - numba==0.57.0
      - numpy==1.24.2
      - openpyxl==3.1.2
      - packaging==24.2
      - pandas==1.5.3
      - parmed==4.3.0
      - pathspec==0.12.1
      - patsy==1.0.1
      - periodictable==1.7.1
      - pillow==9.5.0
      - platformdirs==4.3.6
      - plotly==5.13.0
      - pluggy==1.5.0
      - pre-commit==3.1.0
      - propcache==0.3.0
      - protgraph==0.3.9
      - psutil==5.9.5
      - pyflakes==3.2.0
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - pyteomics==4.7.2
      - pytest==7.2.1
      - pytest-cov==4.0.0
      - pytest-dependency==0.5.1
      - pytest-django==4.5.2
      - pytest-order==1.1.0
      - pytz==2024.2
      - referencing==0.35.1
      - requests==2.31.0
      - restring==0.1.20
      - rpds-py==0.21.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - spectrum-utils==0.5.0a0
      - sphinx==7.2.6
      - sphinx-autoapi==3.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlparse==0.5.2
      - statsmodels==0.13.5
      - tenacity==9.0.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tqdm==4.65.0
      - umap-learn==0.5.3
      - virtualenv==20.27.1
      - werkzeug==2.2.3
      - yarl==1.18.3
